{
        "name": "timeless.polydawn.io/pcre",
        "releases": [
                {
                        "name": "v8.42",
                        "items": {
                                "src": "tar:2j1zkKRNk3XmKBcEuUi4T18wS8vXYUdRPin2dGjTsrbGJKUXQgM6bib1jyq466b6mF"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}