{
        "name": "timeless.polydawn.io/busybox",
        "releases": [
                {
                        "name": "v1.29.3",
                        "items": {
                                "src": "tar:7ekbC1djrqQJCqL2jJZmU67ugEEus2GHiNVdtw9cZ7MeZJYakF5M9seLFK3QxjcE3p"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}