{
        "name": "timeless.polydawn.io/openssl",
        "releases": [
                {
                        "name": "v1.0.2p",
                        "items": {
                                "src": "tar:7gFxL9E39gjyTgNqtt251Mh76Lc4Frj6SrGhBz8AM4QAhbk7DUsFn1qfPN8dHSjZTV"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}