{
        "name": "timeless.polydawn.io/nginx",
        "releases": [
                {
                        "name": "v1.14.0",
                        "items": {
                                "src": "tar:89nQmhudPsic6DEZkyZ6um2zdCkUp3Lo2BaXbHTgtEms2URh354TTVkQ1HsySfynrq"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}