{
        "name": "timeless.polydawn.io/gawk",
        "releases": [
                {
                        "name": "v4.2.1",
                        "items": {
                                "src": "tar:8ZgoERyn2dxKu5xnBbxQvSBvzrbGbHcN1eFChhcLYffdudH5apmi4faiEF5tP5wWwV"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}