{
        "name": "timeless.polydawn.io/zlib",
        "releases": [
                {
                        "name": "v1.2.11",
                        "items": {
                                "src": "tar:6kXaYq3ym7MLRcgn5az7QSvKDNDMxHKCQJXNaVqkvhMxgDuTgUtND1RiZmGH3Uc3Vf"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}