{
        "name": "timeless.polydawn.io/m4",
        "releases": [
                {
                        "name": "v1.4.18",
                        "items": {
                                "src": "tar:2hEgW64R1fvbViu1MUoKt5qz6mTMhMDS7UuTETb4YJMZFqE5HGYyKExGrwktJ2WYHP"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}