{
        "name": "timeless.polydawn.io/glibc",
        "releases": [
                {
                        "name": "v2.28",
                        "items": {
                                "src": "tar:aBnjqJ1nck6uAHAgnMa4HEtqzYrKgCVXi5QNaj9Wr3NBC6Vh8ooD4WCp83HY7WEri"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}