{
        "name": "timeless.polydawn.io/bison",
        "releases": [
                {
                        "name": "v3.2.2",
                        "items": {
                                "src": "tar:9zwXJ9YPqmhVymMSXAoUNoQ6U2ns6igkYwsK3viJTZCPZzCASmHQ1fZXGEk7Difhju"
                        },
                        "metadata": null,
                        "hazards": null
                },
        ]
}